'use strict';
function createLegacyReview(React, html) {
  const {useState,useEffect,useRef}=React;
  const allowed=ctx=>['owner','admin'].includes(ctx.user?.canonicalRoleKey)&&ctx.user?.capabilities?.includes('organization.manage');
  function BackupHealth({ctx}) {
    const L=(en,ar)=>ctx.lang==='ar'?ar:en;
    const [data,setData]=useState(null),[error,setError]=useState(false),[busy,setBusy]=useState(false);
    const generation=useRef(0);
    const load=async()=>{const g=++generation.current;setBusy(true);setError(false);try{const r=await ctx.rpc('backup_health_v3',{p_org:ctx.organizationId});if(g===generation.current)setData(r);}catch{if(g===generation.current)setError(true);}finally{if(g===generation.current)setBusy(false);}};
    useEffect(()=>{setData(null);if(allowed(ctx))load();return()=>{generation.current++;};},[ctx.organizationId]);
    const labels={HEALTHY:L('Healthy','سليم'),WARNING:L('Needs attention','يحتاج تدخل'),FAILED:L('Failed','فشل'),NOT_CONFIGURED:L('Not configured','غير مفعّل')};
    const date=v=>v?new Date(v).toLocaleString(ctx.lang==='ar'?'ar-EG':'en-GB'):L('Not recorded','غير مسجل');
    if(!allowed(ctx))return html`<p role="alert">${L('Owner or authorized admin access required.','متاح للمالك أو المدير المصرح له فقط.')}</p>`;
    return html`<section class="view legacy-review"><h1>${L('Backups','النسخ الاحتياطي')}</h1><p>${L('Verified recovery evidence. A manual export does not mean a scheduled backup is active.','أدلة استرجاع فعلية. التصدير اليدوي لا يعني تفعيل النسخ المجدول.')}</p><button disabled=${busy} onClick=${load}>${busy?L('Checking…','جارٍ الفحص…'):L('Refresh health','تحديث الحالة')}</button>${error&&html`<p role="alert">${L('Could not load evidence. Retry; no healthy status is assumed.','تعذر تحميل الأدلة. أعد المحاولة؛ لا نفترض نجاح النسخ.')}</p>`}${data&&html`<dl class="review-health">${[
      [L('Status','الحالة'),labels[data.status]||data.status], [L('Database backup','نسخة قاعدة البيانات'),labels[data.database]||data.database],
      [L('Last successful off-device backup','آخر نسخة خارج الجهاز'),date(data.lastSuccessfulBackup)], [L('Next scheduled backup','النسخة المجدولة القادمة'),date(data.nextScheduledBackup)],
      [L('Retention','مدة الاحتفاظ'),data.retentionDays?data.retentionDays+' '+L('days','يوم'):L('Not configured','غير مفعّل')],
      [L('Storage protection','حماية الملفات'),labels[data.storageProtection]||data.storageProtection], [L('Last restore test','آخر اختبار استرجاع'),date(data.lastRestoreTest)],
      [L('Automatic schedule','الجدولة التلقائية'),data.scheduleActive?L('Configured; see freshness above','مفعّلة؛ راجع توقيت آخر نسخة'):L('Owner configuration required','يتطلب إعداد المالك')]
    ].map(([label,value])=>html`<div key=${label}><dt>${label}</dt><dd>${value}</dd></div>`)}</dl>`}</section>`;
  }
  function LegacyReview({ctx}) {
    const L=(en,ar)=>ctx.lang==='ar'?ar:en;
    const [list,setList]=useState(null),[detail,setDetail]=useState(null),[filters,setFilters]=useState({search:'',type:'',risk:'',status:'',client:'',entity:''}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[decision,setDecision]=useState('NEEDS_MORE_INFO'),[target,setTarget]=useState(''),[notes,setNotes]=useState(''),[preview,setPreview]=useState(null),[confirm,setConfirm]=useState(''),[message,setMessage]=useState('');
    const generation=useRef(0),requests=useRef(0),pending=useRef(null),lock=useRef(false),heading=useRef(null);
    const actionLabels={LEAVE_UNCHANGED:L('Leave unchanged','الإبقاء بدون تغيير'),IGNORE_INTENTIONAL:L('Confirm intentional / ignore','تأكيد أن الوضع مقصود'),NEEDS_MORE_INFO:L('Needs more information','معلومات إضافية مطلوبة'),LINK_CONTACTS:L('Link identity references; preserve all records','ربط الهوية مع الاحتفاظ بكل السجلات'),RESTORE_PARENT:L('Restore the referenced archived parent','استعادة السجل الأصلي المؤرشف'),LINK_PROJECT:L('Confirm and link the intended project','تأكيد وربط المشروع المقصود')};
    const statusLabels={OPEN:L('Open','مفتوح'),NEEDS_REVIEW:L('Needs review','يحتاج مراجعة'),DECIDED:L('Decided','القرار محفوظ'),READY_TO_EXECUTE:L('Ready','جاهز'),RESOLVED:L('Resolved','تم الإصلاح'),IGNORED:L('Intentionally unchanged','بدون تغيير مقصود'),NEEDS_MORE_INFO:L('Needs more information','معلومات إضافية'),FAILED:L('Failed; repair rolled back','فشل؛ تم التراجع عن الإصلاح')};
    const typeLabels={CONTACT:L('Contact identity','هوية جهة اتصال'),ASSET:L('Archived relationship','علاقة مؤرشفة'),TASK:L('Task relationship','علاقة مهمة'),IDENTITY:L('Account identity','هوية حساب'),FINANCE:L('Financial projection','ربط مالي'),STORAGE:L('Storage ownership','ملكية ملف'),ROLE:L('Permission policy','سياسة الصلاحيات')};
    const riskLabels={LOW:L('Low','منخفض'),MEDIUM:L('Medium','متوسط'),HIGH:L('High','مرتفع')};
    const fail=()=>setError(L('Not confirmed. Check connection and permissions; reopen the case if another review changed it.','لم يتم التأكيد. تحقق من الاتصال والصلاحيات، وأعد فتح الحالة إذا تغيّرت مراجعتها.'));
    const load=async()=>{const n=++requests.current,g=generation.current;try{const out=await ctx.rpc('list_legacy_review_v3',{p_org:ctx.organizationId,...Object.fromEntries(Object.entries(filters).map(([k,v])=>['p_'+k,v]))});if(n===requests.current&&g===generation.current)setList(out);}catch{if(g===generation.current)fail();}};
    useEffect(()=>{generation.current++;setDetail(null);setList(null);setPreview(null);pending.current=null;return()=>{generation.current++;};},[ctx.organizationId]);
    useEffect(()=>{if(!allowed(ctx))return;const timer=window.setTimeout(load,250);return()=>window.clearTimeout(timer);},[ctx.organizationId,JSON.stringify(filters)]);
    const open=async id=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');setPreview(null);setConfirm('');setMessage('');const g=generation.current;try{const out=await ctx.rpc('get_legacy_review_v3',{p_org:ctx.organizationId,p_case:id});if(g!==generation.current)return;setDetail(out);setDecision(out.case.decision||'NEEDS_MORE_INFO');setTarget(out.case.decision_args?.targetId||'');setNotes(out.case.owner_notes||'');pending.current=null;window.setTimeout(()=>heading.current?.focus(),0);}catch{if(g===generation.current)fail();}finally{lock.current=false;if(g===generation.current)setBusy(false);}};
    const run=async mode=>{if(lock.current||!detail)return;lock.current=true;setBusy(true);setError('');setMessage('');const g=generation.current;
      const args={p_org:ctx.organizationId,p_case:detail.case.id,p_expected:detail.case.version,p_mode:mode,p_decision:decision,p_args:target?{targetId:target}:{},p_notes:notes,p_preview:mode==='EXECUTE'?preview?.previewId:null,p_confirm:mode==='EXECUTE'?confirm:null};const key=JSON.stringify(args);if(pending.current?.key!==key)pending.current={key,id:crypto.randomUUID()};
      try{const out=await ctx.rpc('legacy_review_command_v3',{...args,p_command:pending.current.id});if(g!==generation.current)return;pending.current=null;
        if(mode==='PREVIEW'){setPreview(out);setConfirm('');}else{setPreview(null);setConfirm('');const fresh=await ctx.rpc('get_legacy_review_v3',{p_org:ctx.organizationId,p_case:detail.case.id});if(g!==generation.current)return;setDetail(fresh);setMessage(out.stale?L('Records changed. Nothing executed; review current values and preview again.','تغيّرت السجلات. لم ينفذ الإصلاح؛ راجع القيم الحالية وعاين من جديد.'):out.ok?L('Recorded successfully.','تم التسجيل بنجاح.'):L('Repair rolled back. Check the audit result before retrying.','تم التراجع عن الإصلاح. راجع نتيجة التدقيق قبل المحاولة.'));await load();}
      }catch{if(g===generation.current)fail();}finally{lock.current=false;if(g===generation.current)setBusy(false);}};
    const change=(setter,value)=>{setter(value);setPreview(null);setConfirm('');pending.current=null;};
    const exportSummary=()=>{const rows=(list?.items||[]).map(c=>({caseId:c.case_key,type:c.case_type,status:c.status,decision:c.decision,reviewedBy:c.reviewed_by,reviewedAt:c.reviewed_at,executionStatus:c.execution_status}));const url=URL.createObjectURL(new Blob([JSON.stringify(rows,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='legacy-review-summary.json';a.click();URL.revokeObjectURL(url);};
    if(!allowed(ctx))return html`<p role="alert">${L('Owner or authorized admin access required.','متاح للمالك أو المدير المصرح له فقط.')}</p>`;
    const choices=decision==='LINK_CONTACTS'?(detail?.records||[]):detail?.targets||[];
    return html`<section class="view legacy-review"><header><div class="eyebrow">${L('Settings / Data & Maintenance','الإعدادات / البيانات والصيانة')}</div><h1>${L('Legacy Data Review','مراجعة البيانات القديمة')}</h1><p>${list?list.total+' '+L('cases','حالة')+' / '+list.groups+' '+L('grouped owner decisions','قرار مالك مجمّع'):L('Loading cases…','جارٍ تحميل الحالات…')}</p></header>
    <div class="review-summary">${['OPEN','NEEDS_REVIEW','DECIDED','RESOLVED'].map(s=>html`<div key=${s}><strong>${list?.summary?.[s]||0}</strong><span>${statusLabels[s]}</span></div>`)}<div><strong>${list?.highRisk||0}</strong><span>${L('High risk','مخاطر مرتفعة')}</span></div></div>
    <div class="review-filters"><label>${L('Search case / name / email / phone / reference','بحث بالحالة أو الاسم أو البريد أو الهاتف أو المرجع')}<input value=${filters.search} onInput=${e=>setFilters({...filters,search:e.target.value})}/></label>
    ${[['type',L('Case type','نوع الحالة'),(list?.types||[]).map(v=>[v,typeLabels[v]||v])],['risk',L('Risk','المخاطر'),Object.entries(riskLabels)],['status',L('Status','الحالة'),Object.entries(statusLabels)],['client',L('Client','العميل'),(list?.clients||[]).map(v=>[v.id,v.name])]].map(([k,label,values])=>html`<label key=${k}>${label}<select value=${filters[k]} onChange=${e=>setFilters({...filters,[k]:e.target.value})}><option value="">${L('All','الكل')}</option>${values.map(([v,name])=>html`<option key=${v} value=${v}>${name}</option>`)}</select></label>`)}
    <label>${L('Affected entity ID','معرّف السجل المتأثر')}<input value=${filters.entity} onInput=${e=>setFilters({...filters,entity:e.target.value})}/></label><label>${L('Workspace','مساحة العمل')}<input readOnly value=${ctx.organizationId}/></label></div>
    <div class="flex gap8"><button onClick=${()=>{setError('');load();}}>${L('Refresh','تحديث')}</button><button disabled=${!list} onClick=${exportSummary}>${L('Export filtered summary','تصدير الملخص المصفّى')}</button></div>
    ${error&&html`<p role="alert">${error}</p>`}${message&&html`<p role="status">${message}</p>`}
    <div class="review-layout"><div class="review-table" role="region" aria-label=${L('Review cases','حالات المراجعة')} tabIndex="0"><table><thead><tr>${[L('Case','الحالة'),L('Type / records','النوع / السجلات'),L('Risk','المخاطر'),L('Status','الحالة'),L('Recommended next step','الخطوة المقترحة'),L('Updated','آخر تحديث')].map(s=>html`<th key=${s} scope="col">${s}</th>`)}</tr></thead><tbody>${(list?.items||[]).map(c=>html`<tr key=${c.id}><td><button disabled=${busy} onClick=${()=>open(c.id)}>${c.case_key}</button><small>${c.group_key!==c.case_key?c.group_key:''}</small></td><td>${typeLabels[c.case_type]||c.case_type}<small>${c.record_ids.length} ${L('references','مراجع')}</small></td><td>${riskLabels[c.risk_level]}</td><td>${statusLabels[c.status]||c.status}</td><td>${actionLabels[c.decision]||L('Review evidence; choose an action','راجع الأدلة واختر الإجراء')}</td><td>${new Date(c.updated_at).toLocaleDateString(ctx.lang==='ar'?'ar-EG':'en-GB')}</td></tr>`)}</tbody></table>${list&&!list.items.length&&html`<p>${L('No cases match these filters.','لا توجد حالات مطابقة.')}</p>`}</div>
    ${detail&&html`<section class="review-detail" aria-label=${L('Case details','تفاصيل الحالة')}><button disabled=${busy} onClick=${()=>{setDetail(null);setPreview(null);}}>${L('Close details','إغلاق التفاصيل')}</button><h2 ref=${heading} tabIndex="-1">${detail.case.case_key}</h2><p>${typeLabels[detail.case.case_type]||detail.case.case_type} · ${riskLabels[detail.case.risk_level]} · ${statusLabels[detail.case.status]}</p><h3>${L('Why it needs review','سبب المراجعة')}</h3><p dir="auto">${detail.case.description}</p><p dir="auto">${detail.case.context}</p><p>${L('Group decisions are coordinated, not automatically applied to peers.','قرارات المجموعة مترابطة، ولا تُطبّق تلقائيًا على الحالات الأخرى.')}</p>
    <h3>${L('Current authorized records','السجلات الحالية المصرح بها')}</h3>${detail.records.map(r=>html`<article key=${r.id}><strong dir="auto">${r.name}</strong><p dir="auto">${r.id} · ${r.type} · ${r.archived?L('Archived','مؤرشف'):L('Active','نشط')}</p><p dir="auto">${[r.email,r.phone].filter(Boolean).join(' · ')}</p><dl>${['clientId','projectId','assignedTo','invoiceId'].filter(k=>r[k]).map(k=>html`<div key=${k}><dt>${({clientId:L('Client','العميل'),projectId:L('Project','المشروع'),assignedTo:L('Assignee','المكلّف'),invoiceId:L('Invoice','الفاتورة')})[k]}</dt><dd dir="auto">${r[k]}</dd></div>`)}</dl></article>`)}
    ${!['RESOLVED','IGNORED'].includes(detail.case.status)&&html`<fieldset disabled=${busy}><legend>${L('Owner decision','قرار المالك')}</legend><label>${L('Valid action','الإجراء المتاح')}<select value=${decision} onChange=${e=>{change(setDecision,e.target.value);setTarget('');}}>${detail.options.map(v=>html`<option key=${v} value=${v}>${actionLabels[v]||v}</option>`)}</select></label>
    ${['LINK_CONTACTS','LINK_PROJECT'].includes(decision)&&html`<label>${L('Explicit target','الهدف المختار')}<select value=${target} onChange=${e=>change(setTarget,e.target.value)}><option value="">${L('Choose a verified target','اختر الهدف بعد التحقق')}</option>${choices.map(r=>html`<option key=${r.id} value=${r.id}>${r.name} · ${r.id}</option>`)}</select></label>`}
    <label>${L('Decision notes — do not enter secrets','ملاحظات القرار — لا تدخل أسرارًا')}<textarea maxLength="2000" value=${notes} onInput=${e=>change(setNotes,e.target.value)}/></label><div class="flex gap8"><button onClick=${()=>run('SAVE')}>${L('Save decision for later','حفظ القرار لوقت لاحق')}</button><button onClick=${()=>run('PREVIEW')}>${L('Preview impact','معاينة الأثر')}</button></div>
    ${preview&&html`<div class="review-preview"><h3>${L('Review before execution','راجع قبل التنفيذ')}</h3><p>${actionLabels[decision]}</p><p>${L('No business rows will be deleted. Every affected reference is checked again before the transaction.','لن تُحذف سجلات العمل. سيُعاد التحقق من كل مرجع متأثر قبل تنفيذ العملية.')}</p><dl>${Object.entries(preview.impact).filter(([k])=>!['action','confirmation'].includes(k)).map(([k,v])=>html`<div key=${k}><dt>${({records:L('Affected references','المراجع المتأثرة'),businessRowsDeleted:L('Rows deleted','السجلات المحذوفة'),businessRowsMoved:L('Rows moved','السجلات المنقولة'),warning:L('Scope','النطاق'),preserved:L('Preserved','ما سيُحفظ'),canonicalReference:L('Canonical reference','المرجع الرئيسي'),identityReferencesLinked:L('References linked','المراجع المربوطة'),restoreRecord:L('Restore record','السجل المستعاد'),reactivateArchivedRecord:L('Reactivate archived record','إعادة تفعيل سجل مؤرشف'),affectedChildren:L('Affected children','السجلات المرتبطة'),task:L('Task','المهمة'),oldProject:L('Previous project','المشروع السابق'),newProject:L('New project','المشروع الجديد'),oldClient:L('Previous client','العميل السابق'),newClient:L('New client','العميل الجديد')})[k]||k}</dt><dd dir="auto">${Array.isArray(v)?v.join(', '):typeof v==='boolean'?(v?L('Yes','نعم'):L('No','لا')):k==='warning'?L(String(v),'لا تغلق الحالات المرتبطة تلقائيًا. سيُعاد التحقق من السجلات عند التنفيذ.'):k==='preserved'?L(String(v),decision==='LINK_CONTACTS'?'تبقى كل السجلات والأنشطة والفرص والمعرّفات والتاريخ بدون دمج أو حذف أو استبدال للحقول.':decision==='RESTORE_PARENT'?'تبقى السجلات المرتبطة والتاريخ؛ لا تتغير العلاقات الأخرى.':decision==='LINK_PROJECT'?'تبقى حالة المهمة والمكلّف والاعتماديات والتعليقات وحالة الأرشفة.':'تبقى بيانات العمل بدون تغيير. الإبقاء المقصود لا يُسجل كإصلاح، وطلب المعلومات يظل مفتوحًا.'):String(v??'—')}</dd></div>`)}</dl><label>${L('Type the case ID to confirm','اكتب معرّف الحالة للتأكيد')}<input autoComplete="off" value=${confirm} onInput=${e=>setConfirm(e.target.value)}/></label><button disabled=${confirm!==detail.case.case_key} onClick=${()=>run('EXECUTE')}>${L('Execute confirmed decision','تنفيذ القرار المؤكد')}</button></div>`}</fieldset>`}
    <h3>${L('Permanent audit history','سجل التدقيق الدائم')}</h3>${detail.events.map((e,i)=>html`<article key=${i}><strong>${({SAVE:L('Decision saved','حفظ القرار'),PREVIEW:L('Impact preview','معاينة الأثر'),EXECUTE:L('Execution','التنفيذ')})[e.action]||e.action} · ${actionLabels[e.decision]||e.decision}</strong><p>${new Date(e.at).toLocaleString()} · ${e.actor}</p><p dir="auto">${e.notes}</p><p>${e.result.stale?L('Stale — not executed','تغيّرت البيانات — لم ينفذ'):e.result.reconciliation||L('Decision / preview recorded','تم تسجيل القرار أو المعاينة')}</p></article>`)}</section>`}</div></section>`;
  }
  return {LegacyReview,BackupHealth};
}
window.MagnetLegacyReview={createLegacyReview};
