'use strict';
// New/extracted modules get real linting; the legacy inline app keeps its smoke gate.
module.exports = [
  {
    files: ['magnet-studio/integration.js'],
    languageOptions: {
      globals: {
        docs: 'writable',
        working: 'writable',
        persistWorking: 'writable',
        save: 'writable',
        renderStudio: 'writable',
        exportPDF: 'writable',
        state: 'writable',
        app: 'readonly',
        $: 'readonly',
        blank: 'readonly',
        field: 'readonly',
        esc: 'readonly',
        topbar: 'readonly',
        bind: 'readonly',
        toast: 'readonly',
      },
    },
  },
  {
    files: [
      'api/runtime-config.js',
      'server/runtime-config.js',
      'modules/auth-entry.js',
      'modules/session-refresh.js',
      'modules/crm-followups.js',
      'modules/proposal-revisions.js',
      'modules/client-onboarding.js',
      'modules/project-briefs.js',
      'modules/studio-workspace.js',
      'modules/legacy-review.js',
      'tools/legacy-review-source.js',
      'tools/legacy-review-source-test.js',
      'tools/*backup*.mjs',
      'tools/import-legacy-review.mjs',
      'magnet-studio/integration.js',
      'modules/task-status.js',
      'modules/task-dependencies.js',
      'tools/task-status-test.js',
      'tools/*-database-test.mjs',
      'tools/asset-versions.js',
      'tools/asset-versions-test.js',
      'tools/session-refresh-test.js',
      'tools/csp.js',
      'modules/legacy-compatibility.js',
      'tools/reconcile-data.js',
      'tools/reconciliation-test.js',
      'tools/product-remediation-test.js',
      'tools/{static-files,dev-server,build-static,foundation-test}.js',
      'eslint.config.js',
      'tools/database-test.mjs',
      'tools/workflow-database-test.mjs',
      'tools/conversion-database-test.mjs',
      'tools/followups-database-test.mjs',
      'tools/proposals-database-test.mjs',
      'tools/proposal-public-database-test.mjs',
    ],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'commonjs',
      globals: {
        Blob: 'readonly',
        setTimeout: 'readonly',
        window: 'readonly',
        location: 'readonly',
        crypto: 'readonly',
        document: 'readonly',
        parent: 'readonly',
        NodeFilter: 'readonly',
        URLSearchParams: 'readonly',
        Buffer: 'readonly',
        AbortSignal: 'readonly',
        URL: 'readonly',
        Response: 'readonly',
        fetch: 'readonly',
        console: 'readonly',
        process: 'readonly',
        __dirname: 'readonly',
      },
    },
    rules: {
      'no-undef': 'error',
      'no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      'no-unreachable': 'error',
      'no-dupe-keys': 'error',
      'no-constant-condition': 'error',
      eqeqeq: 'error',
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'valid-typeof': 'error',
      'constructor-super': 'error',
    },
  },
  {
    files: [
      'tools/*backup*.mjs',
      'tools/import-legacy-review.mjs',
      'tools/database-test.mjs',
      'tools/workflow-database-test.mjs',
      'tools/conversion-database-test.mjs',
      'tools/followups-database-test.mjs',
      'tools/proposals-database-test.mjs',
      'tools/proposal-public-database-test.mjs',
      'tools/*-database-test.mjs',
    ],
    languageOptions: { sourceType: 'module' },
  },
];
