'use strict';
// New/extracted modules get real linting; the legacy inline app keeps its smoke gate.
module.exports = [
  {
    files: [
      'api/runtime-config.js',
      'server/runtime-config.js',
      'modules/auth-entry.js',
      'modules/session-refresh.js',
      'modules/crm-followups.js',
      'modules/proposal-revisions.js',
      'modules/client-onboarding.js',
      'modules/project-briefs.js',
      'modules/task-status.js',
      'modules/task-dependencies.js',
      'tools/task-status-test.js',
      'tools/*-database-test.mjs',
      'tools/asset-versions.js',
      'tools/asset-versions-test.js',
      'tools/session-refresh-test.js',
      'tools/csp.js',
      'modules/legacy-compatibility.js',
      'tools/reconcile-data.js',
      'tools/reconciliation-test.js',
      'tools/product-remediation-test.js',
      'tools/{static-files,dev-server,build-static,foundation-test}.js',
      'eslint.config.js',
      'tools/database-test.mjs',
      'tools/workflow-database-test.mjs',
      'tools/conversion-database-test.mjs',
      'tools/followups-database-test.mjs',
      'tools/proposals-database-test.mjs',
      'tools/proposal-public-database-test.mjs',
    ],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'commonjs',
      globals: {
        window: 'readonly',
        Buffer: 'readonly',
        AbortSignal: 'readonly',
        URL: 'readonly',
        Response: 'readonly',
        fetch: 'readonly',
        console: 'readonly',
        process: 'readonly',
        __dirname: 'readonly',
      },
    },
    rules: {
      'no-undef': 'error',
      'no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      'no-unreachable': 'error',
      'no-dupe-keys': 'error',
      'no-constant-condition': 'error',
      eqeqeq: 'error',
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'valid-typeof': 'error',
      'constructor-super': 'error',
    },
  },
  {
    files: [
      'tools/database-test.mjs',
      'tools/workflow-database-test.mjs',
      'tools/conversion-database-test.mjs',
      'tools/followups-database-test.mjs',
      'tools/proposals-database-test.mjs',
      'tools/proposal-public-database-test.mjs',
      'tools/*-database-test.mjs',
    ],
    languageOptions: { sourceType: 'module' },
  },
];
